apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-web-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-web-app
  template:
    metadata:
      name: pod1
      labels:
        app: java-web-app
    spec:
      containers:
      - name: java-web-app
        image: sujankumar861/my-java-web-app:latest
        ports:
        - containerPort: 8080
